import { useRouter } from "next/router"
import Sidebar from "@/components/Sidebar";
import Feed from '@/components/Feed';
import Head from "next/head";
import Widgets from "@/components/Widgets";
import CommentsModal from "@/components/CommentsModal";
import { useEffect, useState } from "react";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";
import Post from "@/components/Post";
import { collection, doc, onSnapshot, orderBy, query } from "firebase/firestore";
import { db } from "@/firebaseconfig";
import Comment from "@/components/Comment";



export default function PostPage() {
    const router = useRouter();
    const [posts,setPosts] = useState(null);
    const [comments,setComments] = useState([]);
    const {postId} = router.query;
    console.log(postId);

    // Get the post Data
    useEffect(()=>{
      try {
        const unsub = onSnapshot(doc(db,'posts',postId),(querySnapshot)=>{
          setPosts(querySnapshot.data())
          // console.log(querySnapshot.data())
          })
            
          return ()=>unsub()
      } catch (error) {
console.log(error.message);        
      }
    },[db,postId])

    // Get the comments data

    useEffect(()=>{
      try {
        const commentsRef = query(collection(db,'posts',postId,'comments'), orderBy('timestamp','desc'));
        const unsub = onSnapshot(commentsRef,(snapShotQuery)=>{
          const comments = snapShotQuery.docs.map(doc=> ({...doc.data(),id:doc.id}))
          setComments(comments);
          console.log(comments);
        })
        
        return ()=>unsub();
      } catch (error) {
        console.log(error.message);
      }
    },[db,postId])

  return (
    <div>

    <Head>
      <title>Post Page</title>
      <meta name='description' content='Generated by  create next app' />
    </Head>
    <main className="flex min-h-screen mx-auto ">
      {/* Sidebar component */}
      <Sidebar />

      {/* Feed component */}
      {/* <Feed /> */}
      <div className="xl:ml-[370px] border-l border-r  border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl  ">
      <div className="sticky top-0 z-50 flex items-center space-x-1  px-3 py-2 bg-white border-b ">
        <div className="hoverEffect hover:bg-blue-200">
          <ArrowLeftIcon className="h-5 " onClick={()=>router.push('/')}/>
        </div>
        <h2 className="text-lg font-bold cursor-pointer sm:text-xl">Tweet</h2>
      </div>
      <Post id={postId}  post={posts}/>
      {
        comments.length > 0 &&(
          <div>
            {
              comments.map((comment)=>(
                <Comment key={comment.id} {...comment}/>
              ))
            }
          </div>
        )
      }
    </div>

      {/* Widgets component */}
{/* <Widgets  followResult={followResult?.results}/> */}
      {/* Modal component */}
      <CommentsModal />
    </main>
    </div>

  )
}







// export async function getServerSideProps(){
//   const top_headlines_api = "top-headlines/category/business/us.json"
//   const BASE_URL = "https://saurav.tech/NewsAPI/"
//   // const data = await fetch(`${BASE_URL}${top_headlines_api}`)
//   // const newsResults = await data.json();

//   // console.log(newsResults);
//   // fetching randomusers
//   const followData = await fetch('https://randomuser.me/api/?results=50&inc=name,login,picture')
//   const followResult = await followData.json()

//   // console.log(followResult);



//   return {
//     props:{
//       // newsResults,
//       followResult
//     }
//   }
  
// }
