import Sidebar from "@/components/Sidebar";
import Feed from '@/components/Feed';
import Head from "next/head";
import Widgets from "@/components/Widgets";
import { useState } from "react";



export default function Home({newsResults:{articles}}) {
  const [articleNum,setArticleNum] =useState(3);
  return (
    <div>

    <Head>
      <title>Chiki-Twitter</title>
      <meta name='description' content='Generated by  create next app' />
    </Head>
    <main className="flex min-h-screen mx-auto ">
      {/* Sidebar component */}
      <Sidebar />

      {/* Feed component */}
      <Feed />

      {/* Widgets component */}
<Widgets newsResults={articles} articleNum={articleNum} setArticleNum={setArticleNum}/>
      {/* Modal component */}
    </main>
    </div>
  )
}



export async function getServerSideProps(){
  const top_headlines_api = "top-headlines/category/business/us.json"
  const BASE_URL = "https://saurav.tech/NewsAPI/"
  const data = await fetch(`${BASE_URL}${top_headlines_api}`)
  const newsResults = await data.json();

  // console.log(newsResults);

  return {
    props:{
      newsResults,
    }
  }
  
}