import Sidebar from "@/components/Sidebar";
import Feed from '@/components/Feed';
import Head from "next/head";
import Widgets from "@/components/Widgets";



export default function Home() {
  return (
    <div>

    <Head>
      <title>Chiki-Twitter</title>
      <meta name='description' content='Generated by  create next app' />
    </Head>
    <main className="flex min-h-screen mx-auto max-w-7xl">
      {/* Sidebar component */}
      <Sidebar />

      {/* Feed component */}
      <Feed />

      {/* Widgets component */}
<Widgets />
      {/* Modal component */}
    </main>
    </div>
  )
}
